feat: update code to have single ibm ip variable
terraform-ibm-modules/terraform-iam-account-settings pull request #36
Opened 2023-04-03 23:34 UTC by jor2

### Description

update code to have single ibm ip variable

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-04-05 17:16 UTC, vburckhardt commented
I think we'll need to maintain an internal wrapper using this module + adding the additional variables that have been removed as internal only.

2023-04-06 13:00 UTC, jor2 commented
> I think we'll need to maintain an internal wrapper using this module + adding the additional variables that have been removed as internal only.

https://github.ibm.com/GoldenEye/iam-account-settings-module/pull/469

2023-04-07 13:08 UTC, ocofaigh commented on variables.tf
> +  description = "Base set of IBM approved IPs, which are documented and sourced from https://pages.github.ibm.com/ibmcloud/Security/guidance/network-access-guidelines.html#pre-approved-ips and https:
This is a public module so we should no reference anything about IBM IPs here...

Rename the variable: `allowed_ip_addresses`
With description: `Defines the IP addresses and subnets from which IAM tokens can be created for the account. Note: value should be a comma separated string.

2023-04-07 13:09 UTC, ocofaigh requested changes
see comment

2023-04-07 15:36 UTC, ocofaigh requested changes
please address failing pre-commit hooks

2023-04-12 09:02 UTC, ocofaigh approved these changes

2023-04-12 09:03 UTC, merged